# Support Vector Machine (SVM)

## Importing the libraries

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [18]:
dataset = pd.read_csv("Social_Network_Ads.csv")
X = dataset.iloc[:,1:-1].values
y = dataset.iloc[:,-1].values

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

## Splitting the dataset into the Training set and Test set

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state = 0)
print(X_train)

[[0 44 39000]
 [1 32 120000]
 [0 38 50000]
 [0 32 135000]
 [0 52 21000]
 [0 53 104000]
 [1 39 42000]
 [1 38 61000]
 [0 36 50000]
 [0 36 63000]
 [0 35 25000]
 [1 35 50000]
 [1 42 73000]
 [0 47 49000]
 [0 59 29000]
 [1 49 65000]
 [0 45 131000]
 [0 31 89000]
 [0 46 82000]
 [0 47 51000]
 [1 26 15000]
 [1 60 102000]
 [0 38 112000]
 [1 40 107000]
 [0 42 53000]
 [1 35 59000]
 [1 48 41000]
 [0 48 134000]
 [0 38 113000]
 [1 29 148000]
 [0 26 15000]
 [1 60 42000]
 [1 24 19000]
 [1 42 149000]
 [0 46 96000]
 [1 28 59000]
 [1 39 96000]
 [1 28 89000]
 [1 41 72000]
 [1 45 26000]
 [0 33 69000]
 [0 20 82000]
 [1 31 74000]
 [1 42 80000]
 [0 35 72000]
 [0 33 149000]
 [1 40 71000]
 [0 51 146000]
 [1 46 79000]
 [1 35 75000]
 [1 38 51000]
 [0 36 75000]
 [0 37 78000]
 [1 38 61000]
 [0 60 108000]
 [0 20 82000]
 [1 57 74000]
 [1 42 65000]
 [1 26 80000]
 [1 46 117000]
 [1 35 61000]
 [0 21 68000]
 [0 28 44000]
 [1 41 87000]
 [0 37 33000]
 [1 27 90000]
 [1 39 42000]
 [1 28 123000]
 [0 31 118000]
 [1 25 87000]
 [0

## Feature Scaling

In [20]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train[:,1:] = sc_x.fit_transform(X_train[:,1:])
X_test[:,1:] = sc_x.transform(X_test[:,1:])

print(X_train)

[[0 0.5816494367283626 -0.8867069898110835]
 [1 -0.6067376076655674 1.4617376807512417]
 [0 -0.012544085468602443 -0.5677824049199036]
 [0 -0.6067376076655674 1.8966348419664871]
 [0 1.3739074663243158 -1.408583583269378]
 [0 1.47293972002381 0.9978473754549799]
 [1 0.08648816823089171 -0.7997275575680345]
 [1 -0.012544085468602443 -0.24885782002872361]
 [0 -0.21060859286759076 -0.5677824049199036]
 [0 -0.21060859286759076 -0.1908715318666909]
 [0 -0.3096408465670849 -1.2926110069453125]
 [1 -0.3096408465670849 -0.5677824049199036]
 [1 0.3835849293293742 0.0990599089434727]
 [0 0.878746197826845 -0.5967755490009199]
 [0 2.067133242220775 -1.1766384306212472]
 [1 1.0768107052258333 -0.13288524370465818]
 [0 0.6806816904278566 1.7806622656424216]
 [0 -0.7057698613650616 0.5629502142397345]
 [0 0.7797139441273508 0.3599982056726199]
 [0 0.878746197826845 -0.5387892608388872]
 [1 -1.2009311298625325 -1.5825424477554761]
 [1 2.166165495920269 0.9398610872929472]
 [0 -0.012544085468602443 1.

## Training the SVM model on the Training set

In [31]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state = 0)
classifier.fit(X_train,y_train)

SVC(random_state=0)

## Predicting a new result

## Predicting the Test set results

In [32]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_pred),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]]


## Making the Confusion Matrix

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score
cfm = confusion_matrix(y_pred,y_test)
acs = accuracy_score(y_pred,y_test)

print(cfm)
print(acs)

[[64  3]
 [ 4 29]]
0.93


## Visualising the Training set results

## Visualising the Test set results